# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "CI build script"

  lane :ci_build do
    git_repo_url = ENV['GIT_REPO_URL']
    git_project_path = ENV['GIT_PROJECT_PATH']
    xcode_project_path = ENV['XCODE_PROJECT_PATH']    

    # 0. clean if needed
    sh("rm -rf #{git_project_path}")

    # 1. Git Clone
    sh("git clone #{git_repo_url}")
    
    # 2. Git Checkout Branch
    sh("cd #{git_project_path} && git checkout main")
    
    # 3: Resolve SPM dependencies
    sh("xcodebuild -project #{xcode_project_path} -resolvePackageDependencies")

    # 4: Match certificate in every target
    # No need for Free Apple developer account.

    # 4. Build the code using gym
    gym(project: "#{xcode_project_path}")

    # 5. Run Unit Tests using scan
    scan(project: "#{xcode_project_path}")

  end
end

